#!/bin/bash
# start gParted on x11
DISP_NUM=$(echo $DISPLAY | cut -d\: -f 2)
echo DISPLAY=localhost:$DISP_NUM XAUTHORITY=/home/pi/.Xauthority gparted
sudo DISPLAY=localhost:$DISP_NUM XAUTHORITY=/home/pi/.Xauthority gparted
