#!/bin/bash
#
# updated by ...: Loreto Notarantonio
# Version ......: 31-08-2020 09.23.07
#

#########################################################################
#
#########################################################################
function @createDirLink() {
    local source_path=$1
    local dest_link_path=$2


    local real_sourcePath="$(readlink -fvs  $source_path)" # resolve links if any
    local real_destPath="$(readlink -fvs  $dest_link_path)" # resolve links if any


    if [[ ! -e "$source_path" ]] || [[ ! -d "$source_path" ]]; then
        @lnLog "${cyanH}${source_path}: ${redH}is NOT a directory, cannot proceed!${colorReset}"
        return 1

    elif [ ! -e "${dest_link_path}" ]; then
        echo -en "${yellowH}"
        @lnEsegui "ln -sf ${real_sourcePath} ${dest_link_path}"
        @lnEsegui "chmod -w ${real_sourcePath}"


    #... fare il test di -L prima di -d e -f
    elif [[ -L "${dest_link_path}"  ]]; then
        if [ "$real_destPath" == "${real_sourcePath}" ]; then
            @lnLog "${yellowH}dirLink OK --> ${cyanH}${dest_link_path} ${greenH}${real_sourcePath}${colorReset}"
        else
            @lnLog "${cyanH}${real_destPath} - ${redH}wrong pointer, creating new one ${colorReset}"
            @lnEsegui "ln -sf ${real_sourcePath} ${dest_link_path}"
        fi

    elif [[ -f "${dest_link_path}"  ]]; then
        @lnLog "${cyanH}${dest_link_path} - ${redH}already exists as FILE. Please remove it manually${colorReset}"
        return 1

    elif [[ -d "${dest_link_path}"  ]]; then
        @lnLog "${cyanH}${dest_link_path} - ${redH}already exists as Directory. Please remove it manually${colorReset}"
        return 1


    else
        @lnLog "${purpleH}${source_path}    unManaged${colorReset}"
        @lnLog "${purpleH}${dest_link_path} unManaged${colorReset}"
    fi
    # echo
}




#########################################################################
#
#########################################################################
function @createFileLink() {
    local source_path=$1
    local dest_link_path=$2



    if [[ ! -e "$source_path" ]]; then
        @lnLog "${redH}$source_path not exists!"
        return 1
    fi
    #... il check non va fatti sul real_destPath
    if [[ -d "${dest_link_path}"  ]]; then
        @lnLog "${redH}destination path is a directory, cannot proceed! -  ${cyanH}${dest_link_path} ${colorReset}"
        return 1
    fi


    local real_sourcePath="$(readlink -fvs  $source_path)" # resolve links if any
    # local real_destPath="$(readlink -fvs  $dest_link_path)" # resolve links if any

    ###... if exists dest as a LINK
    if [[ -L "${dest_link_path}"  ]]; then
        pointingTo="$(readlink -f ${dest_link_path})"
        if [ "${pointingTo}" == "${real_sourcePath}" ]; then
            @lnLog "${yellowH}fileLink OK --> ${cyanH}${dest_link_path} ${greenH}${real_sourcePath}${colorReset}"
        else
            @lnLog "${redH}wrong pointer ${cyanH}${real_destPath} ${colorReset}"
            @lnEsegui "ln -sf ${real_sourcePath} ${dest_link_path}"
        fi

    ###... if exists dest as a FILE
    elif [[ -f "${dest_link_path}"  ]]; then
        @lnLog "${cyanH}${dest_link_path} ${redH}already exists as FILE. Please remove it manually${colorReset}"

    elif [ -f "${real_sourcePath}" ]; then
        echo -en "${yellowH}"
        @lnEsegui "chmod -w ${real_sourcePath}"
        @lnEsegui "ln -sf ${real_sourcePath} ${dest_link_path}"

    else
        @lnLog "${purpleH}${real_sourcePath} NOT FOUND${colorReset}"
    fi
    # echo
}






#########################################################################
#
#########################################################################
# function @createLink() {
#     local source_path=$1
#     local dest_link_path=$2
#     local action=$3


#     if [[ ! -e "$source_path" ]]; then
#         @lnLog "${redH}$source_path not exists!"
#         return 1
#     fi

#     if [[ ! -e "${source_path}"  ]]; then
#         @lnLog "${cyanH}${sourceFile}${TABredH}${source_path} doesn't exists${colorReset}"
#         exit 1
#     elif [[ -d "${source_path}"  ]]; then
#         @createDirLink $source_path $dest_link_path
#     elif [[ -f "${source_path}"  ]]; then
#         @createFileLink $source_path $dest_link_path
#     else
#         @lnLog "${cyanH}${sourceFile}${TABredH}${source_path} is not file neither directory${colorReset}"
#         exit 1
#     fi

# }



# ----------------------------------------------
# ---  by Loreto
# updated by ...: Loreto Notarantonio
# Date .........: 15-11-2025 16.38.24
# ----------------------------------------------
function set_desktopLinks() {
    cd ${HOME}
    local source_desktop_dir="${HOME}/filu/lnEnv/start_proc/.desktop"
    local dest_link_path="${HOME}/.local/share/applicationszz"

    local fname=""

    desktop_files=$(find "${source_desktop_dir}"  -type f -name '*.desktop' | sort) # *.function potrebbe essere sotto diverse directories
    for filename in ${desktop_files}; do
        [ -f "$filename" ] || continue
        fname=$(basename $filename)
        # @createFileLink "$filename" "${dest_link_path}/$fname" "${fEXECUTE}"
    done

    source_path='/home/loreto/filu/lnEnv/shScripts'; dirname=$(basename $source_path)
    @createDirLink ${source_path} "${dest_link_path}/${dirname}" "${fEXECUTE}"

}

source esegui.functions
fEXECUTE=${1:---no-go}

set -u
# echo $BASH_SOURCE
# set_externalDiskLinks
set_desktopLinks