#!/bin/sh
# A script for setting up routing tables for MPTCP in the N950.

# http://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting
# Copy this script into /etc/network/if-post-down.d/

set -e

env > /etc/network/if_down_env

# ==================================================
# definisce le seguenti funzioni:
#   lnLogger
#   flashRoutes
#   setUpRoutes
#   setWlan0
#   setWlan1
#   setEth0
thisSCRIPT=$(basename $0)
moduleName=$(basename $0)
now=$(date +"%Y/%m/%d %H:%M:%S")

# ==================================================
    source "/home/pi/Loreto/etc/LnCommon/LnNetFunctions" $thisSCRIPT
    # se fallisce la lettura del file LnNetFunctions ... esci
    echo "thisHost = $thisHost"
    [[ -z "$thisHost" ]]         && echo "Skipping LnNetFunction ....." && exit 0
# ==================================================


    [[ -z "$IFACE" ]]            && exit 0
    [[ "$IFACE" ==  *"lo"* ]]    && exit 0
    [[ "$IFACE" ==  *"--all"* ]] && exit 0
    [[ "$MODE" != 'stop' ]]      && exit 0

        # chiama la funzione con il nome della vlan
    [[ "$IFACE" ==  *"wlan0"* ]] && setWlan0
    [[ "$IFACE" ==  *"wlan1"* ]] && setWlan1
    [[ "$IFACE" ==  *"eth0"* ]]  && setEth0

    wrLog "$moduleName" "$LINENO" "   interfaceName:      $IFACE"
    wrLog "$moduleName" "$LINENO" "   MODE:               $MODE"
    wrLog "$moduleName" "$LINENO" "   interfaceName:      $interfaceName"
    wrLog "$moduleName" "$LINENO" "   NET:                $NET"
    wrLog "$moduleName" "$LINENO" "   MASK:               $MASK"
    wrLog "$moduleName" "$LINENO" "   IPADDR:             $IPADDR"
    wrLog "$moduleName" "$LINENO" "   GATEWAY:            $GATEWAY"
    wrLog "$moduleName" "$LINENO" "   TABLE_NAME:         $TABLE_NAME"
    wrLog "$moduleName" "$LINENO" "   ------------------------ "
    bringDOWNInterface
    wrLog "$moduleName" "$LINENO" ""
    exit 0
