generic:







LIBRI:
    Contemporarey:
        Paola Chiozza:
            Thunder. La potenza dell'amore

        Lauren Asher:
            Throttled. Partenza

        Silveie Basset:
            Principe di ghiaccio:
                tra l'amore proibito e il desiderio

        Rachel Reid:
            Time to shine:
                A spicy bisexual Hocker romance

        Rina Kent:
            Beatiful Venom:
                The most addictive dark hockey romance

        Jennifer Sucevic:
            Solo per una notte
            Se fossi mia

        Dennis Grover Swank:
            Aftermath (sport romance post universitario)

        SierraLewis:
            Odio amore e Hockey

        R.C. Stephens:
            The player.02: Solo una notte



    # Mi piacciono Ana Huang e Vi Keeland per il loro modo di scrivere. Esiste qualche autrice simile che scrive thriller romantici (senza mafia)? (in italiano)
    # Thriller con romance per adulti che scrivono stile Ana Huang e Vi Keeland. Italiano e no mafia.
    Thriller:
        Blair Thorne:
            Black label series

        Penelope Douglas:
            L'errore che rifarei

        Vi Keeland:
            Someone knows
            The Unravelling

        Giusy Andaloro:
            La porta dimensionale