Virtual Servers

ID              Service Port    Internal Port   IP Address  Protocol
SSH             22022            22             192.168.1.22  TCP
SSH             23022            22             192.168.1.23  TCP
SSH             31022            22             192.168.1.31  TCP

FTP             31021            21             192.168.1.31  TCP

https           22443            443            192.168.1.22  TCP
https           23443            443            192.168.1.23  TCP
https           31443            443            192.168.1.31  TCP
Mosquitto       1883             1883           192.168.1.23  TCP
Mosquitto       1884             1883           192.168.1.31  TCP
RDP             31389            3389           192.168.1.31  TCP
amule           4711-4712        4711-4712      192.168.1.23  ALL
amule           4662-4672        4662-4672      192.168.1.23  ALL
HomeAssistant   8123             8123           192.168.1.41  TCP
