Virtual Servers

Name                    Protocol    WAN port    LAN port    Destination IP  Destination MAC
Brother Printer         TCP         60080       80          192.168.1.12    18:4F:32:26:AA:CF
FTP LnPi41              TCP         41021       21          192.168.1.41    DC:A6:32:BA:C9:F5
HomeAssistant           TCP         8123        8123        192.168.1.41    DC:A6:32:BA:C9:F5
Mosquitto LnPi41        TCP         1883        1883        192.168.1.41    DC:A6:32:BA:C9:F5
MySQL server            TCP         3306        3306        192.168.1.41    DC:A6:32:BA:C9:F5
MySQL server            UDP         3306        3306        192.168.1.41    DC:A6:32:BA:C9:F5
TSM01 - sonoff          TCP         50051       80          192.168.1.51    DC:4F:22:92:DF:AF
VNC LnPi41              TCP         5941        5900        192.168.1.41    DC:A6:32:BA:C9:F5
XRDP LnPi41             TCP         41389       3389        192.168.1.41    DC:A6:32:BA:C9:F5
amule 4662              TCP         4662        4662        unknown         B8:27:EB:F1:56:67
amule upd               UDP         4665:4672   4665:4672   unknown         B8:27:EB:F1:56:67
amule web               TCP         4711:4712   4711:4712   unknown         B8:27:EB:F1:56:67
httpd-443               TCP         41443       443         192.168.1.41    DC:A6:32:BA:C9:F5
httpd-80                TCP         41080       80          192.168.1.41    DC:A6:32:BA:C9:F5
ssh LnPi31 via LnPi41   TCP         41031       41031       192.168.1.41    DC:A6:32:BA:C9:F5
ssh LnPi41              TCP         41022       22          192.168.1.41    DC:A6:32:BA:C9:F5